
CREATE TABLE [dbo].[DMNGAYNGHI](
	[Id] [uniqueidentifier] NOT NULL,
	[Ngay] [date] NULL,
	[MoTa] [nvarchar](255) NULL,
 CONSTRAINT [PK_DMNGAYNGHI] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DMNGAYNGHI] ADD  CONSTRAINT [DF_DMNGAYNGHI_Id]  DEFAULT (newid()) FOR [Id]
GO


